M48
; DRILL file {KiCad 8.0.8-2.fc41} date 2025-02-22T17:19:49+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-22T17:19:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-2.fc41
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X90.0Y-45.137
X90.0Y-135.137
X130.0Y-45.137
X130.0Y-135.137
M30
